CREATE ROLE IF NOT EXISTS DBT_ROLE;

GRANT USAGE
ON WAREHOUSE RETAIL_WH
TO ROLE DBT_ROLE;

GRANT USAGE
ON DATABASE RETAIL_PIPELINE
TO ROLE DBT_ROLE;

GRANT USAGE
ON SCHEMA RETAIL_PIPELINE.RAW TO ROLE DBT_ROLE;

GRANT USAGE
ON SCHEMA RETAIL_PIPELINE.SILVER TO ROLE DBT_ROLE;

GRANT USAGE
ON SCHEMA RETAIL_PIPELINE.GOLD TO ROLE DBT_ROLE;

GRANT USAGE
ON SCHEMA RETAIL_PIPELINE.REFERENCE TO ROLE DBT_ROLE;

GRANT USAGE
ON SCHEMA RETAIL_PIPELINE.SNAPSHOTS TO ROLE DBT_ROLE;

GRANT SELECT
ON ALL TABLES IN SCHEMA RETAIL_PIPELINE.RAW
TO ROLE DBT_ROLE;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA RETAIL_PIPELINE.RAW
TO ROLE DBT_ROLE;



GRANT CREATE TABLE,
      CREATE VIEW
ON SCHEMA RETAIL_PIPELINE.SILVER
TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA RETAIL_PIPELINE.SILVER
TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA RETAIL_PIPELINE.SILVER
TO ROLE DBT_ROLE;


GRANT CREATE TABLE,
      CREATE VIEW
ON SCHEMA RETAIL_PIPELINE.GOLD
TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA RETAIL_PIPELINE.GOLD
TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA RETAIL_PIPELINE.GOLD
TO ROLE DBT_ROLE;


GRANT SELECT
ON ALL TABLES IN SCHEMA RETAIL_PIPELINE.REFERENCE
TO ROLE DBT_ROLE;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA RETAIL_PIPELINE.REFERENCE
TO ROLE DBT_ROLE;


GRANT CREATE TABLE
ON SCHEMA RETAIL_PIPELINE.SNAPSHOTS
TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA RETAIL_PIPELINE.SNAPSHOTS
TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA RETAIL_PIPELINE.SNAPSHOTS
TO ROLE DBT_ROLE;


GRANT ROLE DBT_ROLE
TO USER ApurvaLearns;

USE ROLE DBT_ROLE;

